$cd "D:\Converted"
$modelname "skyrim\chaurus.mdl"
$model "studio" "chaurus_reference.SMD"
$poseparameter move_yaw -180.00 180.00
$cdmaterials "models\skyrim\chaurus\"
$hboxset "default"
$hbox 103 "Pelvis [Pelv]" -17.046  -16.530  -21.828  18.402  20.280  21.828
$hbox 102 "Ribcage[Spn3]" -18.876  -15.942  -21.426  18.390  20.616  21.426
$hbox 102 "[Neck0]" -3.144  -8.454  -18.474  12.060  15.846  18.474
$hbox 102 "[Neck1]" -7.092  -8.616  -18.966  15.180  14.442  18.966
$hbox 102 "[Neck2]" -9.870  -9.054  -18.474  14.142  12.744  18.474
$hbox 102 "[Neck3]" -8.544  -10.314  -18.966  9.216  11.340  18.960
$hbox 101 "NPC Head [Head]" -14.718  -10.674  -19.608  29.766  10.488  19.608
$hbox 101 "Head[LeftPincher]" -0.162  -4.332  -5.310  17.298  4.902  2.544
$hbox 101 "Head[RightPincher]" -0.126  -4.350  -2.424  17.298  4.890  5.478
$hbox 105 "R UpperArm[RClv]" -0.378  -3.180  -2.622  12.924  3.738  3.432
$hbox 105 "R UpperArm[RUar]" -3.174  -4.026  -2.922  26.094  6.498  3.846
$hbox 105 "R UpperArm[RLar]" -1.614  -6.942  -1.524  31.422  1.374  2.832
$hbox 104 "L UpperArm[RClv]" -0.384  -3.186  -3.432  12.912  3.732  2.622
$hbox 104 "L UpperArm[LUar]" -1.296  -4.020  -3.846  26.112  6.498  2.922
$hbox 104 "L UpperArm[LLar]" -1.602  -6.942  -2.832  31.416  1.368  1.536
$hbox 109 "Tail[Tal0]" -1.968  -18.204  -16.818  15.984  15.042  16.818
$hbox 109 "Tail[Tal1]" -10.782  -15.348  -15.918  19.560  13.050  15.864
$hbox 109 "Tail[Tal2]" -5.352  -9.540  -12.918  18.180  8.478  12.990
$hbox 109 "Tail[Tal3]" -11.604  -7.416  -12.798  11.004  9.636  13.116
$hbox 109 "[TalRightPincher]" -1.746  -2.424  -5.316  28.770  2.946  4.176
$hbox 109 "[TalLeftPincher]" -1.746  -2.424  -4.176  28.770  2.946  5.316
$hbox 107 "R Leg[RThg0]" 0.000  -2.904  -2.712  12.552  3.066  3.060
$hbox 107 "R Leg[RThg1]" -0.564  -4.158  -3.420  28.794  6.336  3.570
$hbox 107 "R Leg[RClf]" -0.330  -3.258  -2.160  27.552  5.550  2.472
$hbox 107 "R Leg[RAnkle]" -1.242  -4.620  -1.368  2.454  2.424  2.448
$hbox 106 "LLeg[RThg0]" 0.000  -2.892  -3.066  12.546  3.084  2.712
$hbox 106 "LLeg[LThg1]" -0.582  -4.098  -3.570  28.788  6.372  3.420
$hbox 106 "LLeg[LClf]" -0.270  -3.132  -2.472  27.624  5.634  2.160
$hbox 106 "LLeg[LAnkle]" -1.116  -4.614  -2.448  2.562  2.460  1.344
$hboxset "default2"
$hbox 103 "Pelvis [Pelv]" -17.046  -16.530  -21.828  180.402  182.280  183.828
$hbox 102 "Ribcage[Spn3]" -18.876  -15.942  -21.426  18.390  20.616  21.426
$hbox 102 "[Neck0]" -3.144  -8.454  -18.474  12.060  15.846  18.474
$hbox 102 "[Neck1]" -7.092  -8.616  -18.966  15.180  14.442  18.966
$hbox 102 "[Neck2]" -9.870  -9.054  -18.474  14.142  12.744  18.474
$hbox 102 "[Neck3]" -8.544  -10.314  -18.966  9.216  11.340  18.960
$hbox 101 "NPC Head [Head]" -14.718  -10.674  -19.608  29.766  10.488  19.608
$hbox 101 "Head[LeftPincher]" -0.162  -4.332  -5.310  17.298  4.902  2.544
$hbox 101 "Head[RightPincher]" -0.126  -4.350  -2.424  17.298  4.890  5.478
$hbox 105 "R UpperArm[RClv]" -0.378  -3.180  -2.622  12.924  3.738  3.432
$hbox 105 "R UpperArm[RUar]" -3.174  -4.026  -2.922  26.094  6.498  3.846
$hbox 105 "R UpperArm[RLar]" -1.614  -6.942  -1.524  31.422  1.374  2.832
$hbox 104 "L UpperArm[RClv]" -0.384  -3.186  -3.432  12.912  3.732  2.622
$hbox 104 "L UpperArm[LUar]" -1.296  -4.020  -3.846  26.112  6.498  2.922
$hbox 104 "L UpperArm[LLar]" -1.602  -6.942  -2.832  31.416  1.368  1.536
$hbox 109 "Tail[Tal0]" -1.968  -18.204  -16.818  15.984  15.042  16.818
$hbox 109 "Tail[Tal1]" -10.782  -15.348  -15.918  19.560  13.050  15.864
$hbox 109 "Tail[Tal2]" -5.352  -9.540  -12.918  18.180  8.478  12.990
$hbox 109 "Tail[Tal3]" -11.604  -7.416  -12.798  11.004  9.636  13.116
$hbox 109 "[TalRightPincher]" -1.746  -2.424  -5.316  28.770  2.946  4.176
$hbox 109 "[TalLeftPincher]" -1.746  -2.424  -4.176  28.770  2.946  5.316
$hbox 107 "R Leg[RThg0]" 0.000  -2.904  -2.712  12.552  3.066  3.060
$hbox 107 "R Leg[RThg1]" -0.564  -4.158  -3.420  28.794  6.336  3.570
$hbox 107 "R Leg[RClf]" -0.330  -3.258  -2.160  27.552  5.550  2.472
$hbox 107 "R Leg[RAnkle]" -1.242  -4.620  -1.368  2.454  2.424  2.448
$hbox 106 "LLeg[RThg0]" 0.000  -2.892  -3.066  12.546  3.084  2.712
$hbox 106 "LLeg[LThg1]" -0.582  -4.098  -3.570  28.788  6.372  3.420
$hbox 106 "LLeg[LClf]" -0.270  -3.132  -2.472  27.624  5.634  2.160
$hbox 106 "LLeg[LAnkle]" -1.116  -4.614  -2.448  2.562  2.460  1.344
// Model uses material "chaurus.vmt"
$attachment "spit" "NPC Head [Head]" 25.20 0.60 -0.00 rotate 0.00 0.00 0.00
$surfaceprop "antlion"
$illumposition 30.675 74.937 -65.606
$sequence aggrowarning1 "aggrowarning1" ACT_IDLE_ANGRY 1 fps 30.00 {
  { event 1100 0 "event_play WarningTail" }
}

$sequence aggrowarning2 "aggrowarning2" ACT_IDLE_ANGRY 1 fps 30.00 {
  { event 1100 0 "event_play WarningCall" }
}

$sequence attackcombobite "attackcombobite" ACT_MELEE_ATTACK1 1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 31 "event_mattack combitea" }
  { event 1100 47 "event_mattack combiteb" }
}

$sequence attackforwardbite "attackforwardbite" ACT_MELEE_ATTACK2 -1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 25 "event_mattack biteforward" }
}

$sequence attackleftside "attackleftside" ACT_MELEE_ATTACK1 1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 14 "event_mattack biteleft" }
}

$sequence attackpowerbite "attackpowerbite" ACT_MELEE_ATTACK1 1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 20 "event_mattack bitepowera" }
  { event 1100 37 "event_mattack bitepowerb" }
}

$sequence attackrbite "attackrbite" ACT_MELEE_ATTACK1 1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 14 "event_mattack biteleftb" }
}

$sequence attackrcbite "attackrcbite" ACT_MELEE_ATTACK1 1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 14 "event_mattack biterleftc" }
}

$sequence attackrchop "attackrchop" ACT_MELEE_ATTACK1 1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 13 "event_mattack chop" }
}

$sequence attackrheadbash "attackrheadbash" ACT_MELEE_ATTACK1 1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 18 "event_mattack headbash" }
}

$animation mdldecompiler_delta.smd "mdldecompiler_delta.smd" fps 30
$animation a_attack_releasespit "a_attack_releasespit" fps 30.000000 subtract mdldecompiler_delta.smd 0

$sequence g_attack_releasespit "a_attack_releasespit" ACT_GESTURE_RANGE_ATTACK1 -1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 2 "event_rattack spit" }
}

$sequence attack_releasespit "attack_releasespit" ACT_RANGE_ATTACK -1 fps 30.00 {
  { event 1100 0 "event_play Attack" }
  { event 1100 2 "event_rattack spit" }
}

$sequence combatidle "combatidle" loop ACT_IDLE_AGITATED 3 fps 30.00
$sequence combatidle1 "combatidle1" ACT_IDLE_AGITATED 1 fps 30.00 {
  { event 1100 0 "event_play Taunt" }
}

$sequence combatidle2 "combatidle2" ACT_IDLE_AGITATED 1 fps 30.00
$sequence combatidle3 "combatidle3" ACT_IDLE_AGITATED 1 fps 30.00
$sequence death "death" ACT_DIESIMPLE -1 fps 30.00 {
  { event 1100 21 "event_dropdead" }
}

$sequence mainidle "mainidle" loop ACT_IDLE 3 fps 30.00
$animation a_WalkS "a_WalkS" loop fps 30.000000
$animation a_WalkE "a_WalkE" loop fps 30.000000
$animation a_WalkN "a_WalkN" loop fps 30.000000
$animation a_WalkW "a_WalkW" loop fps 30.000000
$sequence walk "a_WalkS" loop ACT_WALK -1 fps 30.00 node walking {
  { event 1100 0 "event_emit FootWalkBack" }
  { event 1100 16 "event_emit FootWalkFront" }
  { event 1100 23 "event_emit FootWalkBack" }
  { event 1100 44 "event_emit FootWalkFront" }
  blendwidth 5
  blend move_yaw -180.000000 180.000000
 a_WalkE a_WalkN a_WalkW a_WalkS
}
$animation a_RunS "a_RunS" loop fps 30.000000
$animation a_RunE "a_RunE" loop fps 30.000000
$animation a_RunN "a_RunN" loop fps 30.000000
$animation a_RunW "a_RunW" loop fps 30.000000
$sequence run "a_RunS" loop ACT_RUN -1 fps 30.00 node running {
  { event 1100 12 "event_emit FootWalkBack" }
  { event 1100 13 "event_emit FootWalkFront" }
  { event 1100 28 "event_emit FootWalkFront" }
  { event 1100 29 "event_emit FootWalkBack" }
  blendwidth 5
  blend move_yaw -180.000000 180.000000
 a_RunE a_RunN a_RunW a_RunS
}
$sequence getup "getup" ACT_ROLL_RIGHT -1 fps 30.00 {
  { event 1100 0 "event_getup" }
  { event 1100 15 "event_emit FootWalkFront" }
  { event 1100 18 "event_emit FootWalkBack" }
  { event 1100 25 "event_emit FootWalkFront" }
}

$sequence idle_feed1 "idle_feed1" fps 30.00 {
  { event 1100 0 "event_play Feed" }
}

$sequence idle_feed2 "idle_feed2" fps 30.00 {
  { event 1100 0 "event_play Feed" }
}

$sequence idle_forage "idle_forage" ACT_IDLE 1 fps 30.00
$sequence idle_lookleft "idle_lookleft" ACT_IDLE 1 fps 30.00
$sequence idle_lookright "idle_lookright" ACT_IDLE 1 fps 30.00
$sequence idle_mandible2 "idle_mandible2" ACT_IDLE 1 fps 30.00 {
  { event 1100 0 "event_play Mandibles" }
}

$sequence idle_sleepexit "idle_sleepexit" ACT_SIGNAL2 -1 fps 30.00
$sequence idle_sleep "idle_sleep" loop ACT_IDLE_STIMULATED -1 fps 1.00 {
  { event 1100 9 "event_activity ACT_IDLE_STIMULATED" }
}

$sequence idle_sleepstart "idle_sleepstart" ACT_SIGNAL1 -1 fps 30.00 {
  { event 1100 34 "event_activity ACT_IDLE_STIMULATED" }
}

$sequence recoilrbite "recoilrbite" fps 30.00
$sequence recoilrheadbash "recoilrheadbash" fps 30.00
$sequence spitidle "spitidle" fps 30.00
$sequence staggerdirectional "staggerdirectional" ACT_SMALL_FLINCH -1 fps 30.00
$sequence staggerlar "staggerlar" ACT_SMALL_FLINCH -1 fps 30.00
$sequence staggermid "staggermid" ACT_SMALL_FLINCH -1 fps 30.00
$sequence staggersmall "staggersmall" ACT_SMALL_FLINCH -1 fps 30.00
$sequence turnleft180 "turnleft180" fps 30.00
$sequence turnleft90 "turnleft90" fps 30.00
$sequence turnleftcombat180 "turnleftcombat180" fps 30.00
$sequence turnleftcombat90 "turnleftcombat90" fps 30.00
$sequence ragdoll "ragdoll" ACT_DIERAGDOLL -1 fps 30.00
